# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 10:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=512)),
                ('lastname', models.CharField(blank=True, max_length=512)),
                ('email', models.CharField(blank=True, max_length=512)),
                ('fb_id', models.BigIntegerField(blank=True)),
                ('fb_token', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('fb_name', models.CharField(blank=True, max_length=512)),
                ('fb_image', models.TextField(blank=True)),
                ('gender', models.IntegerField(choices=[(0, '-'), (1, 'Male'), (2, 'Female')], default=0)),
                ('data', models.TextField(default='null')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
