# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-02 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emusic', '0003_auto_20170901_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('music_name', models.CharField(blank=True, max_length=512)),
                ('artist_name', models.CharField(blank=True, max_length=512)),
                ('album_name', models.CharField(blank=True, max_length=512)),
                ('music_image', models.CharField(blank=True, max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'active'), (1, 'inactive')], default=0)),
                ('data', models.TextField(default='null')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
