# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-02 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emusic', '0004_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_url',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
