# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-02 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emusic', '0005_music_music_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='music_image',
        ),
        migrations.RemoveField(
            model_name='music',
            name='music_url',
        ),
        migrations.AddField(
            model_name='music',
            name='genres',
            field=models.IntegerField(choices=[(0, '-'), (1, 'hip hop'), (2, 'rock'), (3, 'classical'), (4, 'electronic'), (5, 'jazz'), (6, 'r&b'), (7, 'pop')], default=0),
        ),
    ]
