# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emusic', '0006_auto_20170902_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('data', models.TextField(default='null')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emusic_music', to='emusic.Music')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emusic_profile', to='emusic.Profile')),
            ],
        ),
    ]
