# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emusic', '0007_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
